# Based on https://github.com/denkiwakame/py-tiny-pkg/blob/main/.github/workflows/test.yml

name: package

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  install-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        pip-install-options: ["", " -e"]
        exclude: # https://github.com/actions/setup-python/issues/875
          - os: macos-latest
            python-version: "3.8"
          - os: macos-latest
            python-version: "3.9"
          - os: macos-latest
            python-version: "3.10"
      max-parallel: 3
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}${{ matrix.pip-install-options }}
    steps:
    - uses: actions/checkout@v3
    - name: setup-python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        architecture: "x64"
    - name: confirm pip version
      run: pip --version
    - name: installation
      run: pip install ${{ matrix.pip-install-options }} .[dev]
    - name: test
      run: python -m pytest --cov
